-- =========================================================
-- HR QR Attendance Scanning App - Complete Supabase Recreate SQL
-- PostgreSQL / Supabase
-- =========================================================
-- WARNING:
-- This script DROPS and RECREATES the HR app tables in public schema.
-- Run only on a fresh Supabase project or after backing up your data.
-- It does NOT drop or recreate Supabase auth.users.
-- Login is handled by Supabase Auth.
-- public.app_users stores app profile/role and links to auth.users via auth_user_id.
-- =========================================================

BEGIN;

-- =========================================================
-- 0. Drop existing app objects
-- =========================================================

DROP VIEW IF EXISTS public.v_pending_requests_summary CASCADE;
DROP VIEW IF EXISTS public.v_employee_attendance_history CASCADE;
DROP VIEW IF EXISTS public.v_today_attendance_summary CASCADE;
DROP VIEW IF EXISTS public.v_attendance_history CASCADE;

DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.audit_logs CASCADE;
DROP TABLE IF EXISTS public.attendance_corrections CASCADE;
DROP TABLE IF EXISTS public.overtime_requests CASCADE;
DROP TABLE IF EXISTS public.leave_requests CASCADE;
DROP TABLE IF EXISTS public.leave_types CASCADE;
DROP TABLE IF EXISTS public.public_holidays CASCADE;
DROP TABLE IF EXISTS public.attendance_logs CASCADE;
DROP TABLE IF EXISTS public.attendance_records CASCADE;
DROP TABLE IF EXISTS public.qr_locations CASCADE;
DROP TABLE IF EXISTS public.employee_schedules CASCADE;
DROP TABLE IF EXISTS public.app_users CASCADE;
DROP TABLE IF EXISTS public.employees CASCADE;
DROP TABLE IF EXISTS public.positions CASCADE;
DROP TABLE IF EXISTS public.departments CASCADE;
DROP TABLE IF EXISTS public.working_schedules CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;

DROP FUNCTION IF EXISTS public.process_qr_attendance(TEXT, TEXT, TEXT, TEXT, NUMERIC, NUMERIC, INET) CASCADE;
DROP FUNCTION IF EXISTS public.can_manage_employee_data(BIGINT) CASCADE;
DROP FUNCTION IF EXISTS public.can_view_employee(BIGINT) CASCADE;
DROP FUNCTION IF EXISTS public.is_manager() CASCADE;
DROP FUNCTION IF EXISTS public.is_admin_or_hr() CASCADE;
DROP FUNCTION IF EXISTS public.current_role_name() CASCADE;
DROP FUNCTION IF EXISTS public.current_employee_id() CASCADE;
DROP FUNCTION IF EXISTS public.current_app_user_id() CASCADE;
DROP FUNCTION IF EXISTS public.set_updated_at() CASCADE;

-- =========================================================
-- 1. Helper trigger function
-- =========================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- =========================================================
-- 2. Master/Core tables
-- =========================================================

CREATE TABLE public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    description TEXT,
    manager_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_departments_updated_at
BEFORE UPDATE ON public.departments
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL UNIQUE,
    description TEXT,
    min_salary NUMERIC(12,2) NOT NULL DEFAULT 0,
    max_salary NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_positions_salary CHECK (min_salary >= 0 AND max_salary >= 0 AND max_salary >= min_salary)
);

CREATE TRIGGER trg_positions_updated_at
BEFORE UPDATE ON public.positions
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.working_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    break_start TIME NULL,
    break_end TIME NULL,
    working_hours NUMERIC(5,2) NOT NULL,
    weekly_working_days INT NOT NULL DEFAULT 5,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_working_schedules_working_hours CHECK (working_hours >= 0),
    CONSTRAINT chk_working_schedules_weekly_days CHECK (weekly_working_days BETWEEN 1 AND 7)
);

CREATE TRIGGER trg_working_schedules_updated_at
BEFORE UPDATE ON public.working_schedules
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender VARCHAR(20),
    date_of_birth DATE,
    phone VARCHAR(50),
    email VARCHAR(150) UNIQUE,
    address TEXT,
    department_id BIGINT NULL,
    position_id BIGINT NULL,
    manager_id BIGINT NULL,
    hire_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_employees_department FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_employees_position FOREIGN KEY (position_id) REFERENCES public.positions(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_employees_manager FOREIGN KEY (manager_id) REFERENCES public.employees(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT chk_employees_status CHECK (status IN ('active', 'inactive', 'resigned', 'terminated'))
);

CREATE INDEX idx_employees_department_id ON public.employees(department_id);
CREATE INDEX idx_employees_position_id ON public.employees(position_id);
CREATE INDEX idx_employees_manager_id ON public.employees(manager_id);
CREATE INDEX idx_employees_status ON public.employees(status);
CREATE INDEX idx_employees_email ON public.employees(email);

CREATE TRIGGER trg_employees_updated_at
BEFORE UPDATE ON public.employees
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.departments
ADD CONSTRAINT fk_departments_manager
FOREIGN KEY (manager_id) REFERENCES public.employees(id)
ON DELETE SET NULL ON UPDATE CASCADE;

-- =========================================================
-- 3. App users
-- =========================================================
-- Supabase Auth handles login/password/session.
-- app_users stores app role/profile link only.

CREATE TABLE public.app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID NULL UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
    employee_id BIGINT NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    role_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_app_users_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_app_users_role FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_app_users_auth_user_id ON public.app_users(auth_user_id);
CREATE INDEX idx_app_users_employee_id ON public.app_users(employee_id);
CREATE INDEX idx_app_users_role_id ON public.app_users(role_id);
CREATE INDEX idx_app_users_is_active ON public.app_users(is_active);
CREATE INDEX idx_app_users_email ON public.app_users(email);

CREATE TRIGGER trg_app_users_updated_at
BEFORE UPDATE ON public.app_users
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =========================================================
-- 4. Security helper functions for RLS
-- =========================================================

CREATE OR REPLACE FUNCTION public.current_app_user_id()
RETURNS BIGINT
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT au.id
    FROM public.app_users au
    WHERE au.auth_user_id = auth.uid()
      AND au.is_active = TRUE
    LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.current_employee_id()
RETURNS BIGINT
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT au.employee_id
    FROM public.app_users au
    WHERE au.auth_user_id = auth.uid()
      AND au.is_active = TRUE
    LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.current_role_name()
RETURNS TEXT
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT r.name
    FROM public.app_users au
    JOIN public.roles r ON r.id = au.role_id
    WHERE au.auth_user_id = auth.uid()
      AND au.is_active = TRUE
    LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.is_admin_or_hr()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT COALESCE(public.current_role_name() IN ('Admin', 'HR Manager'), FALSE);
$$;

CREATE OR REPLACE FUNCTION public.is_manager()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT COALESCE(public.current_role_name() = 'Manager', FALSE);
$$;

CREATE OR REPLACE FUNCTION public.can_view_employee(target_employee_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT COALESCE(
        public.is_admin_or_hr()
        OR target_employee_id = public.current_employee_id()
        OR EXISTS (
            SELECT 1
            FROM public.employees e
            WHERE e.id = target_employee_id
              AND e.manager_id = public.current_employee_id()
        ),
        FALSE
    );
$$;

CREATE OR REPLACE FUNCTION public.can_manage_employee_data(target_employee_id BIGINT)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT COALESCE(
        public.is_admin_or_hr()
        OR EXISTS (
            SELECT 1
            FROM public.employees e
            WHERE e.id = target_employee_id
              AND e.manager_id = public.current_employee_id()
        ),
        FALSE
    );
$$;

-- =========================================================
-- 5. Operational tables
-- =========================================================

CREATE TABLE public.employee_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    schedule_id BIGINT NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_employee_schedules_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_employee_schedules_schedule FOREIGN KEY (schedule_id) REFERENCES public.working_schedules(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT chk_employee_schedules_dates CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE INDEX idx_employee_schedules_employee_id ON public.employee_schedules(employee_id);
CREATE INDEX idx_employee_schedules_schedule_id ON public.employee_schedules(schedule_id);
CREATE INDEX idx_employee_schedules_effective_dates ON public.employee_schedules(effective_from, effective_to);

CREATE TABLE public.qr_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    qr_code_value VARCHAR(255) NOT NULL UNIQUE,
    location VARCHAR(255),
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_qr_locations_qr_code_value ON public.qr_locations(qr_code_value);
CREATE INDEX idx_qr_locations_is_active ON public.qr_locations(is_active);

CREATE TRIGGER trg_qr_locations_updated_at
BEFORE UPDATE ON public.qr_locations
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    check_in TIMESTAMPTZ NULL,
    check_out TIMESTAMPTZ NULL,
    worked_hours NUMERIC(5,2) NOT NULL DEFAULT 0,
    late_minutes INT NOT NULL DEFAULT 0,
    early_leave_minutes INT NOT NULL DEFAULT 0,
    overtime_minutes INT NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'present',
    note TEXT,
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_attendance_records_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_attendance_records_created_by FOREIGN KEY (created_by) REFERENCES public.app_users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_attendance_records_updated_by FOREIGN KEY (updated_by) REFERENCES public.app_users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT uq_attendance_employee_date UNIQUE (employee_id, attendance_date),
    CONSTRAINT chk_attendance_records_status CHECK (status IN (
        'present', 'absent', 'late', 'early_leave', 'half_day', 'on_leave', 'public_holiday', 'missing_checkout', 'missing_checkin'
    )),
    CONSTRAINT chk_attendance_records_minutes CHECK (
        late_minutes >= 0 AND early_leave_minutes >= 0 AND overtime_minutes >= 0 AND worked_hours >= 0
    )
);

CREATE INDEX idx_attendance_records_employee_id ON public.attendance_records(employee_id);
CREATE INDEX idx_attendance_records_date ON public.attendance_records(attendance_date);
CREATE INDEX idx_attendance_records_status ON public.attendance_records(status);

CREATE TRIGGER trg_attendance_records_updated_at
BEFORE UPDATE ON public.attendance_records
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.attendance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    attendance_record_id BIGINT NULL,
    log_type VARCHAR(30) NOT NULL,
    attendance_type VARCHAR(30) NOT NULL DEFAULT 'qr_code',
    log_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    qr_code_value VARCHAR(255) NULL,
    device_id VARCHAR(100),
    location VARCHAR(255),
    latitude NUMERIC(10,7) NULL,
    longitude NUMERIC(10,7) NULL,
    ip_address VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_attendance_logs_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_attendance_logs_attendance_record FOREIGN KEY (attendance_record_id) REFERENCES public.attendance_records(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT chk_attendance_logs_type CHECK (log_type IN ('check_in', 'check_out', 'break_in', 'break_out')),
    CONSTRAINT chk_attendance_logs_attendance_type_qr_code CHECK (attendance_type = 'qr_code')
);

CREATE INDEX idx_attendance_logs_employee_id ON public.attendance_logs(employee_id);
CREATE INDEX idx_attendance_logs_attendance_record_id ON public.attendance_logs(attendance_record_id);
CREATE INDEX idx_attendance_logs_log_time ON public.attendance_logs(log_time);
CREATE INDEX idx_attendance_logs_log_type ON public.attendance_logs(log_type);
CREATE INDEX idx_attendance_logs_qr_code_value ON public.attendance_logs(qr_code_value);

CREATE TABLE public.public_holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    khmer_name VARCHAR(150),
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_public_holidays_date ON public.public_holidays(holiday_date);

CREATE TABLE public.leave_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    paid BOOLEAN NOT NULL DEFAULT TRUE,
    max_days_per_year NUMERIC(5,2) NOT NULL DEFAULT 0,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_leave_types_max_days CHECK (max_days_per_year >= 0)
);

CREATE TABLE public.leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    leave_type_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_days NUMERIC(5,2) NOT NULL,
    reason TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    approved_by BIGINT NULL,
    approved_at TIMESTAMPTZ NULL,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_leave_requests_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_leave_requests_leave_type FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_leave_requests_approved_by FOREIGN KEY (approved_by) REFERENCES public.employees(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT chk_leave_requests_dates CHECK (end_date >= start_date),
    CONSTRAINT chk_leave_requests_total_days CHECK (total_days > 0),
    CONSTRAINT chk_leave_requests_status CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled'))
);

CREATE INDEX idx_leave_requests_employee_id ON public.leave_requests(employee_id);
CREATE INDEX idx_leave_requests_leave_type_id ON public.leave_requests(leave_type_id);
CREATE INDEX idx_leave_requests_dates ON public.leave_requests(start_date, end_date);
CREATE INDEX idx_leave_requests_status ON public.leave_requests(status);

CREATE TRIGGER trg_leave_requests_updated_at
BEFORE UPDATE ON public.leave_requests
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.overtime_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    attendance_record_id BIGINT NULL,
    overtime_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    total_hours NUMERIC(5,2) NOT NULL,
    rate_percent NUMERIC(6,2) NOT NULL DEFAULT 150.00,
    reason TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    approved_by BIGINT NULL,
    approved_at TIMESTAMPTZ NULL,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_overtime_requests_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_overtime_requests_attendance_record FOREIGN KEY (attendance_record_id) REFERENCES public.attendance_records(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_overtime_requests_approved_by FOREIGN KEY (approved_by) REFERENCES public.employees(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT chk_overtime_requests_total_hours CHECK (total_hours > 0),
    CONSTRAINT chk_overtime_requests_rate CHECK (rate_percent > 0),
    CONSTRAINT chk_overtime_requests_status CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled'))
);

CREATE INDEX idx_overtime_requests_employee_id ON public.overtime_requests(employee_id);
CREATE INDEX idx_overtime_requests_attendance_record_id ON public.overtime_requests(attendance_record_id);
CREATE INDEX idx_overtime_requests_date ON public.overtime_requests(overtime_date);
CREATE INDEX idx_overtime_requests_status ON public.overtime_requests(status);

CREATE TRIGGER trg_overtime_requests_updated_at
BEFORE UPDATE ON public.overtime_requests
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.attendance_corrections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    attendance_record_id BIGINT NULL,
    requested_check_in TIMESTAMPTZ NULL,
    requested_check_out TIMESTAMPTZ NULL,
    reason TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    approved_by BIGINT NULL,
    approved_at TIMESTAMPTZ NULL,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_attendance_corrections_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_attendance_corrections_attendance_record FOREIGN KEY (attendance_record_id) REFERENCES public.attendance_records(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_attendance_corrections_approved_by FOREIGN KEY (approved_by) REFERENCES public.employees(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT chk_attendance_corrections_status CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled'))
);

CREATE INDEX idx_attendance_corrections_employee_id ON public.attendance_corrections(employee_id);
CREATE INDEX idx_attendance_corrections_attendance_record_id ON public.attendance_corrections(attendance_record_id);
CREATE INDEX idx_attendance_corrections_status ON public.attendance_corrections(status);

CREATE TRIGGER trg_attendance_corrections_updated_at
BEFORE UPDATE ON public.attendance_corrections
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    action VARCHAR(100) NOT NULL,
    table_name VARCHAR(100) NOT NULL,
    record_id BIGINT NULL,
    old_value JSONB NULL,
    new_value JSONB NULL,
    ip_address VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES public.app_users(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX idx_audit_logs_user_id ON public.audit_logs(user_id);
CREATE INDEX idx_audit_logs_table_name ON public.audit_logs(table_name);
CREATE INDEX idx_audit_logs_record_id ON public.audit_logs(record_id);
CREATE INDEX idx_audit_logs_created_at ON public.audit_logs(created_at);

CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    notification_type VARCHAR(50) NOT NULL DEFAULT 'info',
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    read_at TIMESTAMPTZ NULL,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES public.app_users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT chk_notifications_type CHECK (notification_type IN ('info', 'success', 'warning', 'error'))
);

CREATE INDEX idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX idx_notifications_is_read ON public.notifications(is_read);
CREATE INDEX idx_notifications_created_at ON public.notifications(created_at);

-- =========================================================
-- 6. QR attendance processing RPC function
-- =========================================================

CREATE OR REPLACE FUNCTION public.process_qr_attendance(
    p_qr_code_value TEXT,
    p_log_type TEXT,
    p_device_id TEXT DEFAULT NULL,
    p_location TEXT DEFAULT NULL,
    p_latitude NUMERIC DEFAULT NULL,
    p_longitude NUMERIC DEFAULT NULL,
    p_ip_address INET DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_app_user_id BIGINT;
    v_employee_id BIGINT;
    v_now TIMESTAMPTZ := now();
    v_today DATE := (now() AT TIME ZONE 'Asia/Phnom_Penh')::date;
    v_local_now TIMESTAMP := (now() AT TIME ZONE 'Asia/Phnom_Penh');
    v_qr_location_id BIGINT;
    v_record_id BIGINT;
    v_log_id BIGINT;
    v_check_in TIMESTAMPTZ;
    v_check_out TIMESTAMPTZ;
    v_start_time TIME;
    v_late_minutes INT := 0;
    v_message TEXT;
BEGIN
    IF p_log_type NOT IN ('check_in', 'check_out', 'break_in', 'break_out') THEN
        RAISE EXCEPTION 'Invalid log type: %', p_log_type;
    END IF;

    v_app_user_id := public.current_app_user_id();
    v_employee_id := public.current_employee_id();

    IF v_app_user_id IS NULL OR v_employee_id IS NULL THEN
        RAISE EXCEPTION 'No active app user / employee profile is linked to this Supabase Auth user.';
    END IF;

    SELECT id INTO v_qr_location_id
    FROM public.qr_locations
    WHERE qr_code_value = p_qr_code_value
      AND is_active = TRUE
    LIMIT 1;

    IF v_qr_location_id IS NULL THEN
        RAISE EXCEPTION 'Invalid or inactive QR code.';
    END IF;

    SELECT ws.start_time INTO v_start_time
    FROM public.employee_schedules es
    JOIN public.working_schedules ws ON ws.id = es.schedule_id
    WHERE es.employee_id = v_employee_id
      AND es.effective_from <= v_today
      AND (es.effective_to IS NULL OR es.effective_to >= v_today)
      AND ws.is_active = TRUE
    ORDER BY es.effective_from DESC
    LIMIT 1;

    IF v_start_time IS NOT NULL THEN
        v_late_minutes := GREATEST(FLOOR(EXTRACT(EPOCH FROM (v_local_now - (v_today + v_start_time))) / 60)::INT, 0);
    END IF;

    INSERT INTO public.attendance_records (
        employee_id,
        attendance_date,
        status,
        created_by,
        updated_by
    )
    VALUES (
        v_employee_id,
        v_today,
        'present',
        v_app_user_id,
        v_app_user_id
    )
    ON CONFLICT (employee_id, attendance_date) DO NOTHING;

    SELECT id, check_in, check_out
    INTO v_record_id, v_check_in, v_check_out
    FROM public.attendance_records
    WHERE employee_id = v_employee_id
      AND attendance_date = v_today;

    IF p_log_type = 'check_in' THEN
        IF v_check_in IS NULL THEN
            UPDATE public.attendance_records
            SET check_in = v_now,
                late_minutes = v_late_minutes,
                status = CASE WHEN v_late_minutes > 0 THEN 'late' ELSE 'present' END,
                updated_by = v_app_user_id
            WHERE id = v_record_id
            RETURNING check_in, check_out INTO v_check_in, v_check_out;
            v_message := 'Check-in successful.';
        ELSE
            v_message := 'Check-in already exists. New scan log was saved, but check-in was not overwritten.';
        END IF;
    ELSIF p_log_type = 'check_out' THEN
        IF v_check_in IS NULL THEN
            UPDATE public.attendance_records
            SET check_out = v_now,
                status = 'missing_checkin',
                updated_by = v_app_user_id
            WHERE id = v_record_id
            RETURNING check_in, check_out INTO v_check_in, v_check_out;
            v_message := 'Checkout saved, but check-in is missing.';
        ELSE
            UPDATE public.attendance_records
            SET check_out = v_now,
                worked_hours = ROUND((EXTRACT(EPOCH FROM (v_now - check_in)) / 3600.0)::NUMERIC, 2),
                status = CASE WHEN status = 'late' THEN 'late' ELSE 'present' END,
                updated_by = v_app_user_id
            WHERE id = v_record_id
            RETURNING check_in, check_out INTO v_check_in, v_check_out;
            v_message := 'Checkout successful.';
        END IF;
    ELSIF p_log_type IN ('break_in', 'break_out') THEN
        v_message := 'Break scan log saved.';
    END IF;

    INSERT INTO public.attendance_logs (
        employee_id,
        attendance_record_id,
        log_type,
        attendance_type,
        log_time,
        qr_code_value,
        device_id,
        location,
        latitude,
        longitude,
        ip_address
    )
    VALUES (
        v_employee_id,
        v_record_id,
        p_log_type,
        'qr_code',
        v_now,
        p_qr_code_value,
        p_device_id,
        p_location,
        p_latitude,
        p_longitude,
        p_ip_address::TEXT
    )
    RETURNING id INTO v_log_id;

    RETURN jsonb_build_object(
        'success', TRUE,
        'message', v_message,
        'attendance_record_id', v_record_id,
        'log_id', v_log_id,
        'employee_id', v_employee_id,
        'attendance_date', v_today,
        'check_in', v_check_in,
        'check_out', v_check_out
    );
END;
$$;

-- =========================================================
-- 7. Seed data
-- =========================================================

INSERT INTO public.roles (id, name, description) VALUES
(1, 'Admin', 'Full system access'),
(2, 'HR Manager', 'Manage employees, attendance, leave, overtime, and reports'),
(3, 'Manager', 'View and approve own team records'),
(4, 'Employee', 'View own profile and submit requests');

INSERT INTO public.departments (id, name, description) VALUES
(1, 'Human Resources', 'Manage employees and company HR policies'),
(2, 'Information Technology', 'Manage software, hardware, and IT systems'),
(3, 'Accounting', 'Manage finance, payroll, and accounting'),
(4, 'Sales', 'Manage sales and customer relationships'),
(5, 'Operations', 'Manage daily business operations');

INSERT INTO public.positions (id, title, description, min_salary, max_salary) VALUES
(1, 'General Manager', 'Manage company operations and teams', 2000.00, 4000.00),
(2, 'HR Manager', 'Responsible for HR management', 1200.00, 2500.00),
(3, 'IT Manager', 'Manage IT team and systems', 1200.00, 2600.00),
(4, 'Software Developer', 'Develop and maintain software systems', 800.00, 2000.00),
(5, 'Accountant', 'Manage accounting and finance records', 700.00, 1800.00),
(6, 'Sales Executive', 'Handle customer sales and follow-up', 500.00, 1500.00),
(7, 'Operations Officer', 'Support daily operations', 500.00, 1300.00);

INSERT INTO public.working_schedules
(id, name, start_time, end_time, break_start, break_end, working_hours, weekly_working_days, description)
VALUES
(1, 'Standard Office Schedule', '08:00:00', '17:00:00', '12:00:00', '13:00:00', 8.00, 5, 'Monday to Friday, 8 hours per day'),
(2, 'Cambodia 48 Hours Schedule', '08:00:00', '17:00:00', '12:00:00', '13:00:00', 8.00, 6, 'Monday to Saturday, 48 hours per week'),
(3, 'Morning Shift', '07:00:00', '15:00:00', '11:00:00', '12:00:00', 7.00, 6, 'Morning shift schedule'),
(4, 'Night Shift', '22:00:00', '06:00:00', NULL, NULL, 8.00, 6, 'Night shift schedule');

INSERT INTO public.employees
(id, employee_code, first_name, last_name, gender, date_of_birth, phone, email, address, department_id, position_id, manager_id, hire_date, status)
VALUES
(1, 'EMP-0001', 'Sok', 'Dara', 'Male', '1988-03-12', '012345678', 'dara@example.com', 'Phnom Penh, Cambodia', 5, 1, NULL, '2021-01-10', 'active'),
(2, 'EMP-0002', 'Chan', 'Sophea', 'Female', '1990-07-20', '012111222', 'sophea@example.com', 'Phnom Penh, Cambodia', 1, 2, 1, '2021-03-01', 'active'),
(3, 'EMP-0003', 'Philip', 'Bardon', 'Male', '1995-05-15', '012222333', 'philip@example.com', 'Phnom Penh, Cambodia', 2, 3, 1, '2022-06-15', 'active'),
(4, 'EMP-0004', 'Vibol', 'Kim', 'Male', '1992-09-02', '012333444', 'vibol@example.com', 'Phnom Penh, Cambodia', 2, 4, 3, '2022-08-01', 'active'),
(5, 'EMP-0005', 'Srey', 'Nita', 'Female', '1998-12-05', '012444555', 'nita@example.com', 'Phnom Penh, Cambodia', 4, 6, 1, '2023-01-20', 'active'),
(6, 'EMP-0006', 'Pheak', 'Rith', 'Male', '1997-11-11', '012555666', 'rith@example.com', 'Phnom Penh, Cambodia', 5, 7, 1, '2023-07-01', 'active');

UPDATE public.departments SET manager_id = 2 WHERE id = 1;
UPDATE public.departments SET manager_id = 3 WHERE id = 2;
UPDATE public.departments SET manager_id = 1 WHERE id = 3;
UPDATE public.departments SET manager_id = 5 WHERE id = 4;
UPDATE public.departments SET manager_id = 1 WHERE id = 5;

-- Demo app users. auth_user_id is NULL until you create/login Supabase Auth users and link by email.
INSERT INTO public.app_users
(id, auth_user_id, employee_id, username, email, role_id, is_active)
VALUES
(1, NULL, 1, 'admin', 'dara@example.com', 1, TRUE),
(2, NULL, 2, 'hr.manager', 'sophea@example.com', 2, TRUE),
(3, NULL, 3, 'manager.philip', 'philip@example.com', 3, TRUE),
(4, NULL, 4, 'vibol', 'vibol@example.com', 4, TRUE),
(5, NULL, 5, 'nita', 'nita@example.com', 4, TRUE),
(6, NULL, 6, 'rith', 'rith@example.com', 4, TRUE);

INSERT INTO public.employee_schedules (id, employee_id, schedule_id, effective_from, effective_to) VALUES
(1, 1, 1, '2024-01-01', NULL),
(2, 2, 1, '2024-01-01', NULL),
(3, 3, 1, '2024-01-01', NULL),
(4, 4, 1, '2024-01-01', NULL),
(5, 5, 1, '2024-01-01', NULL),
(6, 6, 2, '2024-01-01', NULL);

INSERT INTO public.qr_locations (id, name, qr_code_value, location, latitude, longitude, is_active) VALUES
(1, 'Main Office Entrance', 'HR_QR_MAIN_OFFICE_001', 'Phnom Penh Main Office', 11.5564000, 104.9282000, TRUE),
(2, 'Warehouse Entrance', 'HR_QR_WAREHOUSE_001', 'Operations Warehouse', 11.5500000, 104.9200000, TRUE);

INSERT INTO public.public_holidays (id, holiday_date, name, khmer_name, description) VALUES
(1, '2026-01-01', 'International New Year Day', 'ទិវាចូលឆ្នាំសកល', 'Public holiday'),
(2, '2026-04-14', 'Khmer New Year Day 1', 'ពិធីបុណ្យចូលឆ្នាំខ្មែរ ថ្ងៃទី ១', 'Public holiday'),
(3, '2026-04-15', 'Khmer New Year Day 2', 'ពិធីបុណ្យចូលឆ្នាំខ្មែរ ថ្ងៃទី ២', 'Public holiday'),
(4, '2026-04-16', 'Khmer New Year Day 3', 'ពិធីបុណ្យចូលឆ្នាំខ្មែរ ថ្ងៃទី ៣', 'Public holiday'),
(5, '2026-05-01', 'International Labour Day', 'ទិវាពលកម្មអន្តរជាតិ', 'Public holiday');

INSERT INTO public.leave_types (id, name, paid, max_days_per_year, description, is_active) VALUES
(1, 'Annual Leave', TRUE, 18.00, 'Paid annual leave', TRUE),
(2, 'Sick Leave', TRUE, 7.00, 'Paid sick leave', TRUE),
(3, 'Unpaid Leave', FALSE, 30.00, 'Unpaid personal leave', TRUE),
(4, 'Special Leave', TRUE, 7.00, 'Special leave', TRUE);

-- Demo attendance data for today in Cambodia timezone.
INSERT INTO public.attendance_records
(id, employee_id, attendance_date, check_in, check_out, worked_hours, late_minutes, early_leave_minutes, overtime_minutes, status, note, created_by, updated_by)
VALUES
(1, 3, (now() AT TIME ZONE 'Asia/Phnom_Penh')::date, now() - INTERVAL '8 hours', NULL, 0, 0, 0, 0, 'missing_checkout', 'Demo missing checkout', 1, 1),
(2, 4, (now() AT TIME ZONE 'Asia/Phnom_Penh')::date, now() - INTERVAL '7 hours', now() - INTERVAL '1 hour', 6.00, 15, 0, 0, 'late', 'Demo late record', 1, 1),
(3, 5, (now() AT TIME ZONE 'Asia/Phnom_Penh')::date, now() - INTERVAL '8 hours', now() - INTERVAL '30 minutes', 7.50, 0, 0, 0, 'present', 'Demo present record', 1, 1);

INSERT INTO public.attendance_logs
(id, employee_id, attendance_record_id, log_type, attendance_type, log_time, qr_code_value, device_id, location, latitude, longitude, ip_address)
VALUES
(1, 3, 1, 'check_in', 'qr_code', now() - INTERVAL '8 hours', 'HR_QR_MAIN_OFFICE_001', 'demo-device-1', 'Phnom Penh Main Office', 11.5564000, 104.9282000, '127.0.0.1'),
(2, 4, 2, 'check_in', 'qr_code', now() - INTERVAL '7 hours', 'HR_QR_MAIN_OFFICE_001', 'demo-device-2', 'Phnom Penh Main Office', 11.5564000, 104.9282000, '127.0.0.1'),
(3, 4, 2, 'check_out', 'qr_code', now() - INTERVAL '1 hour', 'HR_QR_MAIN_OFFICE_001', 'demo-device-2', 'Phnom Penh Main Office', 11.5564000, 104.9282000, '127.0.0.1');

INSERT INTO public.leave_requests
(id, employee_id, leave_type_id, start_date, end_date, total_days, reason, status, approved_by, approved_at, rejection_reason)
VALUES
(1, 4, 1, '2026-06-10', '2026-06-11', 2.00, 'Family matter', 'approved', 2, now() - INTERVAL '2 days', NULL),
(2, 6, 2, '2026-06-18', '2026-06-18', 1.00, 'Sick leave', 'pending', NULL, NULL, NULL);

INSERT INTO public.overtime_requests
(id, employee_id, attendance_record_id, overtime_date, start_time, end_time, total_hours, rate_percent, reason, status, approved_by, approved_at, rejection_reason)
VALUES
(1, 3, NULL, '2026-06-03', '18:00:00', '20:00:00', 2.00, 150.00, 'Project deadline', 'approved', 2, now() - INTERVAL '3 days', NULL),
(2, 4, NULL, '2026-06-20', '18:00:00', '21:00:00', 3.00, 150.00, 'Urgent support', 'pending', NULL, NULL, NULL);

INSERT INTO public.attendance_corrections
(id, employee_id, attendance_record_id, requested_check_in, requested_check_out, reason, status, approved_by, approved_at, rejection_reason)
VALUES
(1, 6, NULL, NULL, now() - INTERVAL '1 hour', 'Forgot to scan checkout', 'pending', NULL, NULL, NULL);

INSERT INTO public.notifications
(id, user_id, title, message, notification_type, is_read, read_at)
VALUES
(1, 4, 'Leave Approved', 'Your annual leave request has been approved.', 'success', FALSE, NULL),
(2, 3, 'Overtime Approved', 'Your overtime request has been approved.', 'success', FALSE, NULL),
(3, 2, 'Pending Sick Leave Request', 'Pheak Rith submitted a sick leave request.', 'info', FALSE, NULL),
(4, 2, 'Pending Attendance Correction', 'Pheak Rith requested attendance correction for missing checkout.', 'warning', FALSE, NULL);

INSERT INTO public.audit_logs
(id, user_id, action, table_name, record_id, old_value, new_value, ip_address)
VALUES
(1, 1, 'SEED_DATABASE', 'system', NULL, NULL, '{"message":"Initial HR attendance demo data created"}'::jsonb, '127.0.0.1');

-- =========================================================
-- 8. Views
-- =========================================================

CREATE VIEW public.v_attendance_history
WITH (security_invoker = true)
AS
SELECT
    ar.id AS attendance_record_id,
    ar.attendance_date,
    e.id AS employee_id,
    e.employee_code,
    concat(e.first_name, ' ', e.last_name) AS employee_name,
    d.name AS department_name,
    p.title AS position_title,
    ar.check_in,
    ar.check_out,
    ar.worked_hours,
    ar.late_minutes,
    ar.early_leave_minutes,
    ar.overtime_minutes,
    ar.status,
    ar.note
FROM public.attendance_records ar
JOIN public.employees e ON e.id = ar.employee_id
LEFT JOIN public.departments d ON d.id = e.department_id
LEFT JOIN public.positions p ON p.id = e.position_id;

CREATE VIEW public.v_employee_attendance_history
WITH (security_invoker = true)
AS
SELECT * FROM public.v_attendance_history;

CREATE VIEW public.v_today_attendance_summary
WITH (security_invoker = true)
AS
SELECT
    (now() AT TIME ZONE 'Asia/Phnom_Penh')::date AS attendance_date,
    COUNT(e.id) FILTER (WHERE e.status = 'active') AS total_employees,
    COUNT(ar.id) FILTER (WHERE ar.status IN ('present', 'late', 'early_leave', 'missing_checkout')) AS present_today,
    COUNT(ar.id) FILTER (WHERE ar.status = 'late' OR ar.late_minutes > 0) AS late_today,
    COUNT(e.id) FILTER (WHERE e.status = 'active' AND ar.id IS NULL) AS absent_today,
    COUNT(ar.id) FILTER (WHERE ar.check_in IS NOT NULL AND ar.check_out IS NULL) AS missing_checkout,
    COUNT(ar.id) FILTER (WHERE ar.status = 'on_leave') AS on_leave_today
FROM public.employees e
LEFT JOIN public.attendance_records ar
    ON ar.employee_id = e.id
   AND ar.attendance_date = (now() AT TIME ZONE 'Asia/Phnom_Penh')::date;

CREATE VIEW public.v_pending_requests_summary
WITH (security_invoker = true)
AS
SELECT
    (SELECT COUNT(*) FROM public.leave_requests WHERE status = 'pending') AS pending_leave,
    (SELECT COUNT(*) FROM public.overtime_requests WHERE status = 'pending') AS pending_overtime,
    (SELECT COUNT(*) FROM public.attendance_corrections WHERE status = 'pending') AS pending_attendance_corrections;

-- =========================================================
-- 9. Reset identity sequences
-- =========================================================

SELECT setval(pg_get_serial_sequence('public.roles', 'id'), COALESCE((SELECT MAX(id) FROM public.roles), 1), true);
SELECT setval(pg_get_serial_sequence('public.departments', 'id'), COALESCE((SELECT MAX(id) FROM public.departments), 1), true);
SELECT setval(pg_get_serial_sequence('public.positions', 'id'), COALESCE((SELECT MAX(id) FROM public.positions), 1), true);
SELECT setval(pg_get_serial_sequence('public.working_schedules', 'id'), COALESCE((SELECT MAX(id) FROM public.working_schedules), 1), true);
SELECT setval(pg_get_serial_sequence('public.employees', 'id'), COALESCE((SELECT MAX(id) FROM public.employees), 1), true);
SELECT setval(pg_get_serial_sequence('public.app_users', 'id'), COALESCE((SELECT MAX(id) FROM public.app_users), 1), true);
SELECT setval(pg_get_serial_sequence('public.employee_schedules', 'id'), COALESCE((SELECT MAX(id) FROM public.employee_schedules), 1), true);
SELECT setval(pg_get_serial_sequence('public.qr_locations', 'id'), COALESCE((SELECT MAX(id) FROM public.qr_locations), 1), true);
SELECT setval(pg_get_serial_sequence('public.attendance_records', 'id'), COALESCE((SELECT MAX(id) FROM public.attendance_records), 1), true);
SELECT setval(pg_get_serial_sequence('public.attendance_logs', 'id'), COALESCE((SELECT MAX(id) FROM public.attendance_logs), 1), true);
SELECT setval(pg_get_serial_sequence('public.public_holidays', 'id'), COALESCE((SELECT MAX(id) FROM public.public_holidays), 1), true);
SELECT setval(pg_get_serial_sequence('public.leave_types', 'id'), COALESCE((SELECT MAX(id) FROM public.leave_types), 1), true);
SELECT setval(pg_get_serial_sequence('public.leave_requests', 'id'), COALESCE((SELECT MAX(id) FROM public.leave_requests), 1), true);
SELECT setval(pg_get_serial_sequence('public.overtime_requests', 'id'), COALESCE((SELECT MAX(id) FROM public.overtime_requests), 1), true);
SELECT setval(pg_get_serial_sequence('public.attendance_corrections', 'id'), COALESCE((SELECT MAX(id) FROM public.attendance_corrections), 1), true);
SELECT setval(pg_get_serial_sequence('public.audit_logs', 'id'), COALESCE((SELECT MAX(id) FROM public.audit_logs), 1), true);
SELECT setval(pg_get_serial_sequence('public.notifications', 'id'), COALESCE((SELECT MAX(id) FROM public.notifications), 1), true);

-- =========================================================
-- 10. Enable RLS
-- =========================================================

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.working_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qr_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.public_holidays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.overtime_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_corrections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- =========================================================
-- 11. Grants
-- =========================================================

REVOKE ALL ON TABLE public.roles FROM anon;
REVOKE ALL ON TABLE public.departments FROM anon;
REVOKE ALL ON TABLE public.positions FROM anon;
REVOKE ALL ON TABLE public.working_schedules FROM anon;
REVOKE ALL ON TABLE public.employees FROM anon;
REVOKE ALL ON TABLE public.app_users FROM anon;
REVOKE ALL ON TABLE public.employee_schedules FROM anon;
REVOKE ALL ON TABLE public.qr_locations FROM anon;
REVOKE ALL ON TABLE public.attendance_records FROM anon;
REVOKE ALL ON TABLE public.attendance_logs FROM anon;
REVOKE ALL ON TABLE public.public_holidays FROM anon;
REVOKE ALL ON TABLE public.leave_types FROM anon;
REVOKE ALL ON TABLE public.leave_requests FROM anon;
REVOKE ALL ON TABLE public.overtime_requests FROM anon;
REVOKE ALL ON TABLE public.attendance_corrections FROM anon;
REVOKE ALL ON TABLE public.audit_logs FROM anon;
REVOKE ALL ON TABLE public.notifications FROM anon;
REVOKE ALL ON TABLE public.v_attendance_history FROM anon;
REVOKE ALL ON TABLE public.v_employee_attendance_history FROM anon;
REVOKE ALL ON TABLE public.v_today_attendance_summary FROM anon;
REVOKE ALL ON TABLE public.v_pending_requests_summary FROM anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.roles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.departments TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.positions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.working_schedules TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.employees TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.app_users TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.employee_schedules TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.qr_locations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.attendance_records TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.attendance_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.public_holidays TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.leave_types TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.leave_requests TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.overtime_requests TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.attendance_corrections TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.audit_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.notifications TO authenticated;

GRANT SELECT ON TABLE public.v_attendance_history TO authenticated;
GRANT SELECT ON TABLE public.v_employee_attendance_history TO authenticated;
GRANT SELECT ON TABLE public.v_today_attendance_summary TO authenticated;
GRANT SELECT ON TABLE public.v_pending_requests_summary TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT EXECUTE ON FUNCTION public.process_qr_attendance(TEXT, TEXT, TEXT, TEXT, NUMERIC, NUMERIC, INET) TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_app_user_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_employee_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_role_name() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin_or_hr() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_manager() TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_view_employee(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_manage_employee_data(BIGINT) TO authenticated;

-- =========================================================
-- 12. RLS Policies
-- =========================================================

-- Master data
CREATE POLICY "roles_select_authenticated" ON public.roles FOR SELECT TO authenticated USING (true);
CREATE POLICY "roles_manage_admin_hr" ON public.roles FOR ALL TO authenticated USING (public.is_admin_or_hr()) WITH CHECK (public.is_admin_or_hr());

CREATE POLICY "departments_select_authenticated" ON public.departments FOR SELECT TO authenticated USING (true);
CREATE POLICY "departments_manage_admin_hr" ON public.departments FOR ALL TO authenticated USING (public.is_admin_or_hr()) WITH CHECK (public.is_admin_or_hr());

CREATE POLICY "positions_select_authenticated" ON public.positions FOR SELECT TO authenticated USING (true);
CREATE POLICY "positions_manage_admin_hr" ON public.positions FOR ALL TO authenticated USING (public.is_admin_or_hr()) WITH CHECK (public.is_admin_or_hr());

CREATE POLICY "working_schedules_select_authenticated" ON public.working_schedules FOR SELECT TO authenticated USING (true);
CREATE POLICY "working_schedules_manage_admin_hr" ON public.working_schedules FOR ALL TO authenticated USING (public.is_admin_or_hr()) WITH CHECK (public.is_admin_or_hr());

CREATE POLICY "public_holidays_select_authenticated" ON public.public_holidays FOR SELECT TO authenticated USING (true);
CREATE POLICY "public_holidays_manage_admin_hr" ON public.public_holidays FOR ALL TO authenticated USING (public.is_admin_or_hr()) WITH CHECK (public.is_admin_or_hr());

CREATE POLICY "leave_types_select_authenticated" ON public.leave_types FOR SELECT TO authenticated USING (true);
CREATE POLICY "leave_types_manage_admin_hr" ON public.leave_types FOR ALL TO authenticated USING (public.is_admin_or_hr()) WITH CHECK (public.is_admin_or_hr());

-- QR locations
CREATE POLICY "qr_locations_select_active_authenticated" ON public.qr_locations FOR SELECT TO authenticated USING (is_active = true OR public.is_admin_or_hr());
CREATE POLICY "qr_locations_manage_admin_hr" ON public.qr_locations FOR ALL TO authenticated USING (public.is_admin_or_hr()) WITH CHECK (public.is_admin_or_hr());

-- app_users
CREATE POLICY "app_users_select_self_or_admin_hr" ON public.app_users
FOR SELECT TO authenticated
USING (auth_user_id = auth.uid() OR public.is_admin_or_hr());

CREATE POLICY "app_users_insert_admin_hr" ON public.app_users
FOR INSERT TO authenticated
WITH CHECK (public.is_admin_or_hr());

CREATE POLICY "app_users_update_admin_hr" ON public.app_users
FOR UPDATE TO authenticated
USING (public.is_admin_or_hr())
WITH CHECK (public.is_admin_or_hr());


CREATE POLICY "app_users_delete_admin_hr" ON public.app_users
FOR DELETE TO authenticated
USING (public.is_admin_or_hr());

-- employees
CREATE POLICY "employees_select_own_team_or_admin_hr" ON public.employees
FOR SELECT TO authenticated
USING (public.can_view_employee(id));

CREATE POLICY "employees_insert_admin_hr" ON public.employees
FOR INSERT TO authenticated
WITH CHECK (public.is_admin_or_hr());

CREATE POLICY "employees_update_admin_hr" ON public.employees
FOR UPDATE TO authenticated
USING (public.is_admin_or_hr())
WITH CHECK (public.is_admin_or_hr());

CREATE POLICY "employees_delete_admin_hr" ON public.employees
FOR DELETE TO authenticated
USING (public.is_admin_or_hr());

-- employee schedules
CREATE POLICY "employee_schedules_select_own_team_or_admin_hr" ON public.employee_schedules
FOR SELECT TO authenticated
USING (public.can_view_employee(employee_id));

CREATE POLICY "employee_schedules_manage_admin_hr" ON public.employee_schedules
FOR ALL TO authenticated
USING (public.is_admin_or_hr())
WITH CHECK (public.is_admin_or_hr());

-- attendance records
CREATE POLICY "attendance_records_select_own_team_or_admin_hr" ON public.attendance_records
FOR SELECT TO authenticated
USING (public.can_view_employee(employee_id));

CREATE POLICY "attendance_records_insert_admin_hr" ON public.attendance_records
FOR INSERT TO authenticated
WITH CHECK (public.is_admin_or_hr());

CREATE POLICY "attendance_records_update_admin_hr" ON public.attendance_records
FOR UPDATE TO authenticated
USING (public.is_admin_or_hr())
WITH CHECK (public.is_admin_or_hr());

CREATE POLICY "attendance_records_delete_admin_hr" ON public.attendance_records
FOR DELETE TO authenticated
USING (public.is_admin_or_hr());

-- attendance logs
CREATE POLICY "attendance_logs_select_own_team_or_admin_hr" ON public.attendance_logs
FOR SELECT TO authenticated
USING (public.can_view_employee(employee_id));

CREATE POLICY "attendance_logs_insert_own_qr_only" ON public.attendance_logs
FOR INSERT TO authenticated
WITH CHECK (
    employee_id = public.current_employee_id()
    AND attendance_type = 'qr_code'
    AND log_type IN ('check_in', 'check_out', 'break_in', 'break_out')
);

CREATE POLICY "attendance_logs_update_admin_hr" ON public.attendance_logs
FOR UPDATE TO authenticated
USING (public.is_admin_or_hr())
WITH CHECK (public.is_admin_or_hr() AND attendance_type = 'qr_code');

CREATE POLICY "attendance_logs_delete_admin_hr" ON public.attendance_logs
FOR DELETE TO authenticated
USING (public.is_admin_or_hr());

-- leave requests
CREATE POLICY "leave_requests_select_own_team_or_admin_hr" ON public.leave_requests
FOR SELECT TO authenticated
USING (public.can_view_employee(employee_id));

CREATE POLICY "leave_requests_insert_own" ON public.leave_requests
FOR INSERT TO authenticated
WITH CHECK (employee_id = public.current_employee_id() AND status = 'pending');

CREATE POLICY "leave_requests_update_own_pending_to_cancelled" ON public.leave_requests
FOR UPDATE TO authenticated
USING (employee_id = public.current_employee_id() AND status = 'pending')
WITH CHECK (employee_id = public.current_employee_id() AND status IN ('pending', 'cancelled'));

CREATE POLICY "leave_requests_update_manager_admin_hr" ON public.leave_requests
FOR UPDATE TO authenticated
USING (public.can_manage_employee_data(employee_id))
WITH CHECK (public.can_manage_employee_data(employee_id));

CREATE POLICY "leave_requests_delete_admin_hr" ON public.leave_requests
FOR DELETE TO authenticated
USING (public.is_admin_or_hr());

-- overtime requests
CREATE POLICY "overtime_requests_select_own_team_or_admin_hr" ON public.overtime_requests
FOR SELECT TO authenticated
USING (public.can_view_employee(employee_id));

CREATE POLICY "overtime_requests_insert_own" ON public.overtime_requests
FOR INSERT TO authenticated
WITH CHECK (employee_id = public.current_employee_id() AND status = 'pending');

CREATE POLICY "overtime_requests_update_own_pending_to_cancelled" ON public.overtime_requests
FOR UPDATE TO authenticated
USING (employee_id = public.current_employee_id() AND status = 'pending')
WITH CHECK (employee_id = public.current_employee_id() AND status IN ('pending', 'cancelled'));

CREATE POLICY "overtime_requests_update_manager_admin_hr" ON public.overtime_requests
FOR UPDATE TO authenticated
USING (public.can_manage_employee_data(employee_id))
WITH CHECK (public.can_manage_employee_data(employee_id));

CREATE POLICY "overtime_requests_delete_admin_hr" ON public.overtime_requests
FOR DELETE TO authenticated
USING (public.is_admin_or_hr());

-- attendance corrections
CREATE POLICY "attendance_corrections_select_own_team_or_admin_hr" ON public.attendance_corrections
FOR SELECT TO authenticated
USING (public.can_view_employee(employee_id));

CREATE POLICY "attendance_corrections_insert_own" ON public.attendance_corrections
FOR INSERT TO authenticated
WITH CHECK (employee_id = public.current_employee_id() AND status = 'pending');

CREATE POLICY "attendance_corrections_update_own_pending_to_cancelled" ON public.attendance_corrections
FOR UPDATE TO authenticated
USING (employee_id = public.current_employee_id() AND status = 'pending')
WITH CHECK (employee_id = public.current_employee_id() AND status IN ('pending', 'cancelled'));

CREATE POLICY "attendance_corrections_update_manager_admin_hr" ON public.attendance_corrections
FOR UPDATE TO authenticated
USING (public.can_manage_employee_data(employee_id))
WITH CHECK (public.can_manage_employee_data(employee_id));

CREATE POLICY "attendance_corrections_delete_admin_hr" ON public.attendance_corrections
FOR DELETE TO authenticated
USING (public.is_admin_or_hr());

-- audit logs
CREATE POLICY "audit_logs_select_admin_hr" ON public.audit_logs
FOR SELECT TO authenticated
USING (public.is_admin_or_hr());

CREATE POLICY "audit_logs_insert_authenticated" ON public.audit_logs
FOR INSERT TO authenticated
WITH CHECK (public.current_app_user_id() IS NOT NULL);

CREATE POLICY "audit_logs_update_admin_hr" ON public.audit_logs
FOR UPDATE TO authenticated
USING (public.is_admin_or_hr())
WITH CHECK (public.is_admin_or_hr());

CREATE POLICY "audit_logs_delete_admin_hr" ON public.audit_logs
FOR DELETE TO authenticated
USING (public.is_admin_or_hr());

-- notifications
CREATE POLICY "notifications_select_own_or_admin_hr" ON public.notifications
FOR SELECT TO authenticated
USING (user_id = public.current_app_user_id() OR public.is_admin_or_hr());

CREATE POLICY "notifications_insert_admin_hr" ON public.notifications
FOR INSERT TO authenticated
WITH CHECK (public.is_admin_or_hr());

CREATE POLICY "notifications_update_own_or_admin_hr" ON public.notifications
FOR UPDATE TO authenticated
USING (user_id = public.current_app_user_id() OR public.is_admin_or_hr())
WITH CHECK (user_id = public.current_app_user_id() OR public.is_admin_or_hr());

CREATE POLICY "notifications_delete_admin_hr" ON public.notifications
FOR DELETE TO authenticated
USING (public.is_admin_or_hr());

COMMIT;

-- =========================================================
-- 13. After running this file
-- =========================================================
-- Create Supabase Auth users from Dashboard > Authentication > Users.
-- Use emails matching public.app_users.email, for example:
--   dara@example.com       Admin
--   sophea@example.com     HR Manager
--   philip@example.com     Manager
--   vibol@example.com      Employee
--
-- Then link Auth users to app users:
--
-- UPDATE public.app_users au
-- SET auth_user_id = u.id
-- FROM auth.users u
-- WHERE lower(u.email) = lower(au.email)
--   AND au.auth_user_id IS NULL;
--
-- Verify link:
-- SELECT au.id, au.email, au.auth_user_id, r.name AS role
-- FROM public.app_users au
-- JOIN public.roles r ON r.id = au.role_id
-- ORDER BY au.id;
--
-- Test RPC from Ionic Vue:
-- const { data, error } = await supabase.rpc('process_qr_attendance', {
--   p_qr_code_value: 'HR_QR_MAIN_OFFICE_001',
--   p_log_type: 'check_in',
--   p_device_id: 'device-001',
--   p_location: 'Phnom Penh Main Office',
--   p_latitude: 11.5564,
--   p_longitude: 104.9282,
--   p_ip_address: null
-- })
-- =========================================================
