<template>
  <ion-page><ion-header><ion-toolbar><ion-title>Requests</ion-title><ion-button slot="end" fill="clear" @click="load">Refresh</ion-button></ion-toolbar></ion-header><ion-content>
    <ion-segment v-model="segment"><ion-segment-button value="leave"><ion-label>Leave</ion-label></ion-segment-button><ion-segment-button value="overtime"><ion-label>Overtime</ion-label></ion-segment-button><ion-segment-button value="correction"><ion-label>Correction</ion-label></ion-segment-button></ion-segment>
    <app-loading-card v-if="loading" /><ion-list v-else-if="current.length"><ion-item v-for="item in current" :key="item.id"><ion-label><h2>{{ title(item) }}</h2><p>{{ item.reason || "No reason supplied" }}</p></ion-label><status-badge :status="item.status" /><ion-button v-if="item.status === 'pending'" slot="end" color="success" fill="clear" @click="decide(item.id, 'approved')">Approve</ion-button><ion-button v-if="item.status === 'pending'" slot="end" color="danger" fill="clear" @click="openReject(item.id)">Reject</ion-button></ion-item></ion-list><app-empty-state v-else title="No requests" :message="`No ${segment} requests found.`" />
    <ion-alert :is-open="rejectOpen" header="Reject request" :inputs="[{ name: 'reason', type: 'textarea', placeholder: 'Rejection reason' }]" :buttons="[{ text: 'Cancel', role: 'cancel' }, { text: 'Reject', role: 'confirm', handler: (data) => decide(rejectId, 'rejected', data.reason) }]" @did-dismiss="rejectOpen = false" />
    <ion-toast v-model:is-open="toastOpen" :message="toastMessage" :color="toastColor" :duration="3500" />
  </ion-content></ion-page>
</template>
<script setup lang="ts">
import { IonAlert, IonButton, IonContent, IonHeader, IonItem, IonLabel, IonList, IonPage, IonSegment, IonSegmentButton, IonTitle, IonToast, IonToolbar } from "@ionic/vue"; import { computed, onMounted, reactive, ref } from "vue"; import AppEmptyState from "@/components/AppEmptyState.vue"; import AppLoadingCard from "@/components/AppLoadingCard.vue"; import StatusBadge from "@/components/StatusBadge.vue"; import { getCorrectionRequests, getLeaveRequests, getOvertimeRequests, setCorrectionRequestStatus, setLeaveRequestStatus, setOvertimeRequestStatus } from "@/services/requestService"; import { useToast } from "@/composables/useToast";
const segment = ref("leave"); const lists = reactive<Record<string, any[]>>({ leave: [], overtime: [], correction: [] }); const current = computed(() => lists[segment.value]); const loading = ref(false); const rejectOpen = ref(false); const rejectId = ref(0); const { showError, showToast, toastColor, toastMessage, toastOpen } = useToast();
function title(item: any) { return item.start_date ? `${item.start_date} to ${item.end_date}` : item.overtime_date || `Correction #${item.id}`; } async function load() { loading.value = true; try { [lists.leave, lists.overtime, lists.correction] = await Promise.all([getLeaveRequests(), getOvertimeRequests(), getCorrectionRequests()]); } catch (e) { showError(e); } finally { loading.value = false; } } function openReject(id: number) { rejectId.value = id; rejectOpen.value = true; }
async function decide(id: number, status: string, reason?: string) { try { if (segment.value === "leave") await setLeaveRequestStatus(id, status, reason); else if (segment.value === "overtime") await setOvertimeRequestStatus(id, status, reason); else await setCorrectionRequestStatus(id, status, reason); showToast(`Request ${status}.`); await load(); } catch (e) { showError(e); } } onMounted(load);
</script>
