<template>
  <ion-page><ion-header><ion-toolbar><ion-title>Employees</ion-title><ion-button slot="end" fill="clear" @click="openCreate">Add</ion-button></ion-toolbar></ion-header>
    <ion-content><ion-searchbar v-model="search" placeholder="Search name or employee code" /><ion-select v-model="status" class="ion-padding-horizontal" label="Status" interface="popover"><ion-select-option value="">All</ion-select-option><ion-select-option value="active">Active</ion-select-option><ion-select-option value="inactive">Inactive</ion-select-option></ion-select>
      <app-loading-card v-if="loading" /><ion-list v-else-if="filtered.length"><ion-item v-for="employee in filtered" :key="employee.id"><ion-label><h2>{{ employee.first_name }} {{ employee.last_name }}</h2><p>{{ employee.employee_code }} · {{ employee.departments?.name || "No department" }}</p></ion-label><status-badge :status="employee.status" /><ion-button slot="end" fill="clear" @click="toggle(employee)">{{ employee.status === "active" ? "Deactivate" : "Activate" }}</ion-button></ion-item></ion-list><app-empty-state v-else title="No employees" message="No employees match the current filters." />
      <ion-modal :is-open="modalOpen" @did-dismiss="modalOpen = false"><ion-header><ion-toolbar><ion-title>New employee</ion-title><ion-button slot="end" fill="clear" @click="modalOpen = false">Close</ion-button></ion-toolbar></ion-header><ion-content class="ion-padding"><ion-list><ion-item><ion-input v-model="form.employee_code" label="Employee code" label-placement="stacked" /></ion-item><ion-item><ion-input v-model="form.first_name" label="First name" label-placement="stacked" /></ion-item><ion-item><ion-input v-model="form.last_name" label="Last name" label-placement="stacked" /></ion-item><ion-item><ion-input v-model="form.email" type="email" label="Email" label-placement="stacked" /></ion-item><ion-item><ion-input v-model="form.hire_date" type="date" label="Hire date" label-placement="stacked" /></ion-item></ion-list><ion-button expand="block" @click="save">Create employee</ion-button></ion-content></ion-modal>
      <ion-toast v-model:is-open="toastOpen" :message="toastMessage" :color="toastColor" :duration="3500" />
    </ion-content>
  </ion-page>
</template>
<script setup lang="ts">
import { IonButton, IonContent, IonHeader, IonInput, IonItem, IonLabel, IonList, IonModal, IonPage, IonSearchbar, IonSelect, IonSelectOption, IonTitle, IonToast, IonToolbar } from "@ionic/vue";
import { computed, onMounted, reactive, ref } from "vue"; import AppEmptyState from "@/components/AppEmptyState.vue"; import AppLoadingCard from "@/components/AppLoadingCard.vue"; import StatusBadge from "@/components/StatusBadge.vue"; import { createEmployee, getEmployees, updateEmployee } from "@/services/employeeService"; import { useToast } from "@/composables/useToast";
type Employee = Awaited<ReturnType<typeof getEmployees>>[number]; const employees = ref<Employee[]>([]); const search = ref(""); const status = ref(""); const loading = ref(false); const modalOpen = ref(false); const form = reactive({ employee_code: "", first_name: "", last_name: "", email: "", hire_date: new Date().toISOString().slice(0, 10) }); const { showError, showToast, toastColor, toastMessage, toastOpen } = useToast();
const filtered = computed(() => employees.value.filter((e) => (!status.value || e.status === status.value) && `${e.first_name} ${e.last_name} ${e.employee_code}`.toLowerCase().includes(search.value.toLowerCase())));
async function load() { loading.value = true; try { employees.value = await getEmployees(); } catch (e) { showError(e); } finally { loading.value = false; } } function openCreate() { modalOpen.value = true; }
async function save() { try { await createEmployee({ ...form, email: form.email || null }); modalOpen.value = false; showToast("Employee created."); await load(); } catch (e) { showError(e); } }
async function toggle(employee: Employee) { try { await updateEmployee(employee.id, { status: employee.status === "active" ? "inactive" : "active" }); await load(); } catch (e) { showError(e); } } onMounted(load);
</script>
