<template>
  <ion-page><ion-header><ion-toolbar><ion-title>Settings</ion-title><ion-button slot="end" fill="clear" @click="load">Refresh</ion-button></ion-toolbar></ion-header><ion-content>
    <ion-segment v-model="segment" scrollable><ion-segment-button value="qr"><ion-label>QR</ion-label></ion-segment-button><ion-segment-button value="departments"><ion-label>Departments</ion-label></ion-segment-button><ion-segment-button value="positions"><ion-label>Positions</ion-label></ion-segment-button><ion-segment-button value="leaveTypes"><ion-label>Leave Types</ion-label></ion-segment-button></ion-segment>
    <div class="ion-padding"><ion-button expand="block" @click="modalOpen = true">Add {{ segmentLabel }}</ion-button></div>
    <app-loading-card v-if="loading" /><ion-list v-else-if="current.length"><ion-item v-for="item in current" :key="item.id"><ion-label><h2>{{ item.name || item.title }}</h2><p>{{ item.qr_code_value || item.description || "No description" }}</p></ion-label><status-badge v-if="'is_active' in item" :status="item.is_active ? 'active' : 'inactive'" /><ion-toggle v-if="segment === 'qr'" slot="end" :checked="item.is_active" @ion-change="toggleQr(item)" /></ion-item></ion-list><app-empty-state v-else title="No master data" :message="`No ${segmentLabel.toLowerCase()} found.`" />
    <ion-modal :is-open="modalOpen" @did-dismiss="modalOpen = false"><ion-header><ion-toolbar><ion-title>Add {{ segmentLabel }}</ion-title><ion-button slot="end" fill="clear" @click="modalOpen = false">Close</ion-button></ion-toolbar></ion-header><ion-content class="ion-padding"><ion-list><ion-item><ion-input v-model="form.name" :label="segment === 'positions' ? 'Title' : 'Name'" label-placement="stacked" /></ion-item><ion-item v-if="segment === 'qr'"><ion-input v-model="form.code" label="QR code value" label-placement="stacked" /></ion-item><ion-item><ion-textarea v-model="form.description" label="Description / location" label-placement="stacked" /></ion-item></ion-list><ion-button expand="block" @click="save">Create</ion-button></ion-content></ion-modal>
    <div class="ion-padding"><app-logout-button /></div>
    <ion-toast v-model:is-open="toastOpen" :message="toastMessage" :color="toastColor" :duration="3500" />
  </ion-content></ion-page>
</template>
<script setup lang="ts">
import { IonButton, IonContent, IonHeader, IonInput, IonItem, IonLabel, IonList, IonModal, IonPage, IonSegment, IonSegmentButton, IonTextarea, IonTitle, IonToast, IonToggle, IonToolbar } from "@ionic/vue"; import { computed, onMounted, reactive, ref } from "vue"; import AppEmptyState from "@/components/AppEmptyState.vue"; import AppLoadingCard from "@/components/AppLoadingCard.vue"; import AppLogoutButton from "@/components/AppLogoutButton.vue"; import StatusBadge from "@/components/StatusBadge.vue"; import { createQrLocation, updateQrLocation } from "@/services/adminService"; import { createDepartment, createLeaveType, createPosition, getSettingsData } from "@/services/settingsService"; import { useToast } from "@/composables/useToast";
const segment = ref("qr"); const data = reactive<Record<string, any[]>>({ qr: [], departments: [], positions: [], leaveTypes: [] }); const current = computed(() => data[segment.value]); const segmentLabel = computed(() => ({ qr: "QR location", departments: "department", positions: "position", leaveTypes: "leave type" }[segment.value] || segment.value)); const loading = ref(false); const modalOpen = ref(false); const form = reactive({ name: "", code: "", description: "" }); const { showError, showToast, toastColor, toastMessage, toastOpen } = useToast();
async function load() { loading.value = true; try { const result = await getSettingsData(); data.qr = result.qrLocations; data.departments = result.departments; data.positions = result.positions; data.leaveTypes = result.leaveTypes; } catch (e) { showError(e); } finally { loading.value = false; } }
async function save() { try { if (segment.value === "qr") await createQrLocation({ name: form.name, qr_code_value: form.code, location: form.description, is_active: true }); else if (segment.value === "departments") await createDepartment({ name: form.name, description: form.description || null }); else if (segment.value === "positions") await createPosition({ title: form.name, description: form.description || null }); else await createLeaveType({ name: form.name, description: form.description || null }); modalOpen.value = false; showToast(`${segmentLabel.value} created.`); await load(); } catch (e) { showError(e); } }
async function toggleQr(item: any) { try { await updateQrLocation(item.id, { is_active: !item.is_active }); await load(); } catch (e) { showError(e); } } onMounted(load);
</script>
